version: "3.8"
services: 
  api:
    build:
      context: ./chantel-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
  webapp:
    build:
      context: ./chantel-webapp
      dockerfile: Dockerfile
    ports:
      - "80:80"
  